export { default as Navbar } from './navbar/Navbar';
export { default as Footer } from './footer/Footer';
export { default as HomeBanner } from './home/homeBanner/HomeBanner';
export { default as InfoBlock } from './home/infoBlock/InfoBlock';
export { default as KeyBenefits } from './home/keyBenefits/KeyBenefits';
export { default as TradeOnTheGo } from './home/tradeOnTheGo/TradeOnTheGo';
export { default as Community } from './home/community/Community';
export { default as Marketplace } from './home/marketplace/Marketplace';
export { default as Roadmap } from './home/roadmap/Roadmap';
